apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  minReplicas: 1  # Note: minReplicas cannot be 0 in HPA, it must be at least 1
  maxReplicas: 7
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend