---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fast-api-service
  name: fast-api-service
spec:
  selector:
    tier: backend
    track: stable
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
...