apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- hpa-backend.yaml
- secrets.yaml
- db-deployment.yaml
- db-service.yaml
- db-volume.yaml

images:
- name: backend
  newTag: latest
- name: react-app
  newName: test
  newTag: ciao
